language: python

python:
    - "3.7"

before_install:
    - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install:
    - pip install pip==20.1
    - pip install -r requirements.txt

services:
    - mongodb

before_script:
    - mongo modelci --eval 'db.createUser({user:"modelci",pwd:"modelci@2020",roles:["readWrite"]});'

script:
    - python -m pytest tests/

notifications:
    slack: ml-model-ci:SyXxPANcJK5flgmAM7aMaNuV
    email: false