name: modelci
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.3.0
  - absl-py=0.9.0
  - astor=0.8.0
  - attrs=19.3.0
  - blas=1.0
  - blinker=1.4
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2020.1.1
  - cachetools=3.1.1
  - cairo=1.14.12
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - cryptography=2.9.2
  - cudatoolkit=10.1.243
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - freeglut=3.0.0
  - freetype=2.9.1
  - gast=0.2.2
  - glib=2.63.1
  - google-auth=1.14.1
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpcio=1.27.2
  - grpcio-tools=1.16.1
  - h5py=2.8.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - idna=2.9
  - importlib_metadata=1.5.0
  - intel-openmp=2020.1
  - jasper=2.0.14
  - jpeg=9b
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libopencv=3.4.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.11.4
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.9
  - markdown=3.1.1
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.2.0
  - ncurses=6.2
  - ninja=1.9.0
  - oauthlib=3.1.0
  - olefile=0.46
  - opencv=3.4.2
  - openssl=1.1.1g
  - opt_einsum=3.1.0
  - packaging=20.3
  - pcre=8.43
  - pillow=7.1.2
  - pixman=0.38.0
  - pluggy=0.13.1
  - py=1.8.1
  - py-opencv=3.4.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - pytest=5.4.1
  - python=3.7.7
  - pyyaml=5.3.1
  - readline=8.0
  - requests=2.23.0
  - requests-oauthlib=1.3.0
  - rsa=4.0
  - scipy=1.4.1
  - six=1.14.0
  - sqlite=3.31.1
  - tensorboard=2.1.0
  - tensorflow=2.1.0
  - tensorflow-base=2.1.0
  - tensorflow-estimator=2.1.0
  - termcolor=1.1.0
  - tk=8.6.8
  - toolz=0.10.0
  - urllib3=1.25.8
  - wcwidth=0.1.9
  - werkzeug=1.0.1
  - wheel=0.34.2
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.1.7
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
      - betterproto==1.2.3
      - docker==4.2.0
      - future==0.18.2
      - grpclib==0.3.1
      - h2==3.2.0
      - hpack==3.0.0
      - hyperframe==5.2.0
      - mongoengine==0.19.1
      - multidict==4.7.5
      - numpy==1.18.4
      - onnx==1.6.0
      - pip==20.1
      - protobuf==3.12.1
      - pymongo==3.10.1
      - pytest-env==0.6.2
      - setuptools==46.4.0
      - stringcase==1.2.0
      - typing-extensions==3.7.4.2
      - websocket-client==0.57.0
