name: modelci
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.3.0
  - absl-py=0.9.0
  - asn1crypto=1.3.0
  - astor=0.8.0
  - blas=1.0
  - blinker=1.4
  - c-ares=1.15.0
  - ca-certificates=2020.1.1
  - cachetools=3.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.1
  - cryptography=2.8
  - gast=0.2.2
  - google-auth=1.13.1
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - grpcio=1.27.2
  - h5py=2.10.0
  - hdf5=1.10.4
  - idna=2.9
  - intel-openmp=2020.0
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libprotobuf=3.11.4
  - libstdcxx-ng=9.1.0
  - markdown=3.1.1
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.2
  - ninja=1.9.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - oauthlib=3.1.0
  - openssl=1.1.1g
  - opt_einsum=3.1.0
  - protobuf=3.11.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.7.7
  - readline=8.0
  - requests=2.23.0
  - requests-oauthlib=1.3.0
  - rsa=4.0
  - scipy=1.4.1
  - six=1.14.0
  - sqlite=3.31.1
  - tensorboard=2.1.0
  - tensorflow=2.1.0
  - tensorflow-base=2.1.0
  - tensorflow-estimator=2.1.0
  - termcolor=1.1.0
  - tk=8.6.8
  - urllib3=1.25.8
  - werkzeug=1.0.1
  - wheel=0.34.2
  - wrapt=1.12.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
      - betterproto==1.2.3
      - grpclib==0.3.1
      - h2==3.2.0
      - hpack==3.0.0
      - hyperframe==5.2.0
    - mongoengine==0.19.1
    - multidict==4.7.5
      - onnx==1.6.0
    - pip==20.1
    - pymongo==3.10.1
    - setuptools==46.1.3
    - stringcase==1.2.0
      - typing-extensions==3.7.4.2
