name: modelci
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1g
  - python=3.7.7
  - readline=8.0
  - sqlite=3.31.1
  - tk=8.6.8
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - betterproto==1.2.3
    - grpclib==0.3.1
    - h2==3.2.0
    - hpack==3.0.0
    - hyperframe==5.2.0
    - mongoengine==0.19.1
    - multidict==4.7.5
    - pip==20.1
    - pymongo==3.10.1
    - setuptools==46.1.3
    - six==1.14.0
    - stringcase==1.2.0
