apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample_deployment
  namespace: default
  labels:
    application: ml-model-ci-deployment
spec:
  replicas: 1
  minReadySeconds: 15
  selector:
    matchLabels:
        application: ml-model-ci-deployment
  template:
    metadata:
      namespace: default
      labels:
        application: ml-model-ci-deployment
    spec:
      initContainers:
        - name: retrieve_model
          image: ferdinandzhong/s3-bucket-rw-docker:latest
          args: ['read_file.py']
          env:
            - name: AWS_ACCESS_KEY_ID
              value: SAMPLEKEY
            - name: AWS_SECRET_ACCESS_KEY
              value: SAMPLEACCESSKEY
            - name: BUCKET_NAME
              value: ferdinand-own-bucket
            - name: REMOTE_MODEL_PATH
              value: test-objects/naturallanguageprocessingwithpytorch.pdf
            - name: LOCAL_MODEL_DIR
              value: /models
            - name: LOCAL_MODEL_NAME
              value: naturallanguageprocessingwithpytorch.pdf
          volumeMounts:
            - name: models-volume
              mountPath: /models/naturallanguageprocessingwithpytorch.pdf
      containers:
        - name: sample_deployment
          image: mlmodelci/pytorch-serving:latest-gpu
          env:
            - name: BATCH_SIZE
              value: 16
            - name: CUDA_DEVICE_ORDER
              value: PCI_BUS_ID
            - name: CUDA_VISIBLE_DEVICES
              value: 1
            - name: MODEL_NAME
              value: naturallanguageprocessingwithpytorch.pdf
          ports:
            - name: torchscript_http_port
              containerPort: 8000
            - name: torchscript_grpc_port
              containerPort: 8001
          volumeMounts:
            - name: models-volume
              mountPath: /models/naturallanguageprocessingwithpytorch.pdf
      volumes:
        - name: models-volume
          emptyDir: {}