name: serving
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.1.0
  - absl-py=0.8.1
  - astor=0.8.0
  - blas=1.0
  - c-ares=1.15.0
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - cffi=1.13.2
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cupti=10.1.168
  - freetype=2.9.1
  - google-pasta=0.1.8
  - grpcio=1.16.1
  - h5py=2.9.0
  - hdf5=1.10.4
  - intel-openmp=2019.4
  - jpeg=9b
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libprotobuf=3.11.2
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - markdown=3.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.1
  - ninja=1.9.0
  - numpy=1.17.4
  - numpy-base=1.17.4
  - olefile=0.46
  - openssl=1.1.1d
  - pillow=6.2.1
  - pip=19.3.1
  - protobuf=3.11.2
  - pycparser=2.19
  - python=3.7.5
  - pytorch=1.4.0
  - readline=7.0
  - scipy=1.3.2
  - setuptools=42.0.2
  - six=1.13.0
  - sqlite=3.30.1
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - termcolor=1.1.0
  - tk=8.6.8
  - torchvision=0.5.0.dev20191221
  - werkzeug=0.16.0
  - wheel=0.33.6
  - wrapt=1.11.2
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
      - cachetools==4.0.0
      - chardet==3.0.4
      - click==7.0
      - fastapi==0.45.0
      - gast==0.2.2
      - google-auth==1.10.0
      - google-auth-oauthlib==0.4.1
      - h11==0.9.0
      - httptools==0.0.13
      - idna==2.8
      - mongoengine==0.19.1
      - oauthlib==3.1.0
      - opt-einsum==3.1.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.7
      - pydantic==1.3
      - pymongo==3.10.0
      - python-multipart==0.0.5
      - requests==2.22.0
      - requests-oauthlib==1.3.0
      - rsa==4.0
      - starlette==0.12.9
      - tensorboard==2.0.2
      - tensorflow-estimator==2.0.1
      - tensorflow-gpu==2.0.0
      - urllib3==1.25.7
      - uvicorn==0.11.1
      - uvloop==0.14.0
      - websockets==8.1
