name: onnx-serve
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - freetype=2.9.1
  - intel-openmp=2019.4
  - jpeg=9b
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.1
  - ninja=1.9.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1d
  - pillow=7.0.0
  - pip=19.3.1
  - python=3.7.6
  - readline=7.0
  - setuptools=44.0.0
  - sqlite=3.30.1
  - tk=8.6.8
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
      - click==7.0
      - fastapi==0.47.1
      - h11==0.9.0
      - httptools==0.0.13
      - onnx==1.6.0
      - protobuf==3.11.2
      - pydantic==1.3
      - python-multipart==0.0.5
      - six==1.14.0
      - starlette==0.12.9
      - typing-extensions==3.7.4.1
      - uvicorn==0.11.2
      - uvloop==0.14.0
      - websockets==8.1
